branches:
  only:
    - develop
    - master
    - /^greenkeeper/.*$/
language: node_js
node_js:
  - lts/*
dist: xenial
git:
  submodules: false
env:
  global:
    - GIT_SHA=$( git rev-parse HEAD )
    - DOCKERTAG=$( echo $TRAVIS_BRANCH | tr -s "[:punct:]" "-" )
jobs:
  include:
    # Build & Deploy
    - stage: run parallel
      script: npm run build:nuxt
      name: "build:nuxt"
      services:
        - docker
      deploy:
        provider: script
        script: bash ./deploy/deploy.sh -p client
        on:
          branch:
            - develop
            - master
    - script: npm run build:storybook > /dev/null 2>&1
      name: "build:storybook"
      services:
        - docker
      after_success:
        - npm i -g surge
        - bash ./deploy/pull-deploy.sh -p storybook
      deploy:
        provider: script
        script: bash ./deploy/deploy.sh -p storybook
        on:
          branch:
            - develop
            - master
    - script: npm run build:docs
      name: "build:docs"
      services:
        - docker
      after_success:
        - npm i -g surge
        - bash ./deploy/pull-deploy.sh -p vuepress
      deploy:
        provider: script
        script: bash ./deploy/deploy.sh -p vuepress
        on:
          branch:
            - develop
            - master
    # Test
    - script: npm run test:ci
      name: "test:unit"
      after_success:
        - npm i -g codecov
        - codecov
    - script:
        - curl https://gist.githubusercontent.com/schul-cloud-bot/a849c38804174f99ca7818782bf03c00/raw/index.sh > integration-test.sh
        - chmod 700 integration-test.sh
        - bash integration-test.sh
      name: "test:integration"
      env:
        - IT_CLIENT_HOST=nuxtclient
        - IT_CLIENT_PORT=4000
      services:
        - docker
      install:
        - echo "skipping install"
      before_cache:
        - mkdir -p node_modules
    # Lint
    - script: npm run lint:ci
      name: "lint"

cache: npm
before_cache:
  # delete all .cache folders before actually storing the cache.
  # nuxt, storybook and vuepress stores some build artefacts here which invalidates the cache.
  - cd node_modules && find . -name .cache -type d -exec rm -rf {} + && cd ..
  - cd node_modules && find . -name .temp -type d -exec rm -rf {} + && cd ..
notifications:
  email: false
